#Server config and mapping
server:
  error:
    include-message: ALWAYS
  port: 8080
  servlet:
    context-path: /shop/api

#Spring
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:./target/local_db
  mvc:
    format:
      date-time: iso
  activemq:
    broker-url: tcp://localhost:61616
    queues:
      config:
        recovery-interval: 10000
        backoff:
          interval: 1000
          attempts: 5

      delivery-request-queue-name: delivery-request-queue
      delivery-response-queue-name: delivery-response-queue
  banner:
    location: banner.txt